name: Fork Triggered Welcome Issue

on:
  fork:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue in origin repo for forker
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORKER: ${{ github.actor }}
          REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --repo "$REPO" \
            --title "🎉 @$FORKER just forked the repo!" \
            --body "Hi @$FORKER, thanks for forking! Feel free to open issues if you have questions, and check out our onboarding guide in `POST_FORK.md`." \
            --label "fork"
