# .github/workflows/fork-triggered-welcome.yml
name: Fork Triggered Welcome Issue

on:
  fork:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue in origin repo for forker
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORKER: ${{ github.actor }}
          UPSTREAM_REPO: ${{ github.repository }}
          FORK_REPO: ${{ github.event.forkee.full_name }}
        run: |
          BODY=$(cat <<EOF
          Hi @$FORKER!
          
          Fork repo: \`${FORK_REPO}\`
          
          Thank you for forking the repository and getting started with the workshop!
          In this issue, we track your progress. Simply click on milestones that you have achieved, we check that and the next task appears here.
          
          **Next step:** Please enable "Issues" in your forked repository so we can collaborate and track your progress or questions.
          
          To enable issues in your fork:
          
          1. Go to your **"Settings"** in your repository: [https://github.com/$FORK_REPO/settings](https://github.com/$FORK_REPO/settings)
          2. Scroll down to the **"Features"** section.
          3. Check the box labeled **"Issues"**.
          4. You're done! You can now create and track issues in your fork.
          
          Thank you!
          
          In this issue we track your progress throughout the workshop:
          
          - [x] Created GitHub account
          - [x] Fork GitHub repo
          - [ ] Activate issues
          EOF
          )

          gh issue create \
            --repo "$UPSTREAM_REPO" \
            --title "@$FORKER Started participating in the workshop! 🎉" \
            --body "$BODY" \
            --label "newfork"
