name: Fork Triggered Welcome Issue

on:
  fork:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue in origin repo for forker
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORKER: ${{ github.actor }}
          REPO: ${{ github.repository }}
          FORK_FULL_NAME: ${{ github.event.forkee.full_name }}
        run: |
          BODY=$(cat <<EOF
          Hi @$FORKER!

          Fork full name: \`${FORK_FULL_NAME}\`

          Leave a comment when you're ready. If your comment has no question mark, this issue will close and we'll continue in your fork.
          EOF
          )

          gh issue create \
            --repo "$REPO" \
            --title "🎉 @$FORKER just forked the repo!" \
            --body "$BODY" \
            --label "newfork"
