name: Close Newfork Welcome & Follow Up

on:
  issue_comment:
    types: [created]

jobs:
  close-and-followup:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'newfork')
    steps:
      - name: Extract FORK from comment
        id: vars
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          COMMENT_BODY="$(cat <<EOF
          $ISSUE_BODY
          EOF
          )"
          echo "Comment was:"
          echo "$COMMENT_BODY"
          FORK_REPO="$(echo "$COMMENT_BODY" | grep -oP 'Fork repo: `\K[^`]+')"

          echo "Extracted FORK_REPO: $FORK_REPO"

          echo "fork_repo<<EOF" >> "$GITHUB_OUTPUT"
          echo "$FORK_REPO" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create follow-up issue in the fork
        id: followup
        if: "!contains(github.event.comment.body, '?')"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORK_REPO: ${{ steps.vars.outputs.fork_repo }}
          FORKER: ${{ github.actor }}
        run: |

          BODY=$(cat <<EOF
          Hi @$FORKER!

          Fork repo: `${FORK_REPO}`
          
          Thank you for working with me on our preregistration!
          
          **Next step:**  
          Please create a new issue in your repository with the title `Introduction needed`.
          
          **Why is this important?:** 
          We are working together on the preregistration, and the introduction section is still missing. 
          By creating this issue and assigning the label, we can clearly track and assign this task as part of our collaboration. 
          This helps us make sure the introduction will be written and not forgotten.
                    
          **What to do:**
          
          1. Go to your repository: `${FORK_REPO}` → “Issues” tab.
          2. Click “New issue”.
          3. For the title, use a fully self-explanatory description, here `Introduction needed`.
          4. In the issue body, describe the problem clearly and concisely, what do we want to do?
          6. Click “Submit new issue”.
          
          Once you have created the issue, I will close this issue for you. If you have any questions, feel free to ask!
          
          Thank you!
          EOF
          )

          gh issue create \
            --repo "$FORK_REPO" \
            --title "Create an issue in your repo for the missing introduction section with title \`Introduction needed\`." \
            --body "$BODY"

      - name: Close issue if comment has no question mark
        if: "!contains(github.event.comment.body, '?')"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
        run: |
          echo "Closing issue #${{ github.event.issue.number }}"
          gh issue close "${{ github.event.issue.number }}" \
            --comment "Continue here: ${{ steps.followup.outputs.new_issue_url }}" \
            --repo "${{ github.repository }}"
