name: Fork Triggered Welcome Issue

on:
  fork:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue in origin repo for forker
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORKER: ${{ github.actor }}
          REPO: ${{ github.repository }}
          FORK_FULL_NAME: ${{ github.event.forkee.full_name }}
        run: |
          gh issue create \
            --repo "$REPO" \
            --title "🎉 @$FORKER just forked the repo!" \
            --body "Hi @$FORKER!\n\nFork full name: \`${FORK_FULL_NAME}\`\n\nLeave a comment when you're ready. If your comment has no question mark, this issue will close and we'll continue in your fork."
            --label "newfork"
