name: Fork Triggered Welcome Issue

on:
  fork:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue in origin repo for forker
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORKER: ${{ github.actor }}
          UPSTREAM_REPO: ${{ github.repository }}
          FORK_REPO: ${{ github.event.forkee.full_name }}
        run: |
          BODY=$(cat <<EOF
          Hi @$FORKER!
          
          Fork repo: \`${FORK_REPO}\`
          
          Thank you for forking the repository!
          
          **Next step:** Please enable "Issues" in your forked repository so we can collaborate and track your progress or questions.
          
          To enable issues in your fork:
          
          1. Go to your repository: [https://github.com/$FORK_REPO](https://github.com/$FORK_REPO)
          2. Click on **"Settings"**.
          3. Scroll down to the **"Features"** section.
          4. Check the box labeled **"Issues"**.
          5. You're done! You can now create and track issues in your fork.
          
          Once you have enabled issues, please leave a comment here to let us know. If you have any questions, feel free to ask!
          
          Thank you!
          EOF
          )

          gh issue create \
            --repo "$UPSTREAM_REPO" \
            --title "@FORKER Please Enable Issues in Your Forked Repository!" \
            --body "$BODY" \
            --label "newfork"
