name: Fork Triggered Welcome Issue

on:
  fork:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue in origin repo for forker
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORKER: ${{ github.actor }}
          UPSTREAM_REPO: ${{ github.repository }}
          FORK_REPO: ${{ github.event.forkee.full_name }}
        run: |
          BODY=$(cat <<EOF
          Hi @$FORKER!

          Fork repo: \`${FORK_REPO}\`
          
          You now need to setup posit.cloud. Follow these steps:
          
          1. Login
          2. Whatever tbd
          
          Leave a comment when you're ready. If your comment has no question mark, this issue will close and we'll continue in your fork.
          EOF
          )

          gh issue create \
            --repo "$UPSTREAM_REPO" \
            --title "🎉 @$FORKER just forked the repo!" \
            --body "$BODY" \
            --label "newfork"
