name: Close Newfork Welcome & Follow Up

on:
  issue_comment:
    types: [created]

jobs:
  close-and-followup:
    runs-on: ubuntu-latest

    # Only act on issues labeled "newfork"
    if: contains(github.event.issue.labels.*.name, 'newfork')

    steps:
      - name: Extract FORK_FULL_NAME from comment
        id: vars
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          COMMENT_BODY="$(cat <<EOF
          $ISSUE_BODY
          EOF
          )"
          echo "Comment was:"
          echo "$COMMENT_BODY"
          FORK_REPO="$(echo "$COMMENT_BODY" | grep -oP 'Fork full name: `\K[^`]+')"

          echo "Extracted FORK_REPO: $FORK_REPO"

          echo "fork_repo<<EOF" >> "$GITHUB_OUTPUT"
          echo "$FORK_REPO" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Close issue if comment has no question mark
        if: "!contains(steps.vars.outputs.comment, '?')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Closing issue #${{ github.event.issue.number }}"
          gh issue close "${{ github.event.issue.number }}" \
            --repo "${{ github.repository }}" \

      - name: Create follow-up issue in the fork
        if: "!contains(steps.vars.outputs.comment, '?')"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORK_REPO: ${{ steps.vars.outputs.fork_repo }}
        run: |
          gh issue create \
            --repo "$FORK_REPO" \
            --title "📦 Next Steps for Your Fork" \
            --body "Hi\n\nYou're all set! Here are the next steps for the workshop:\n\n1. Do this\n2. Check that\n3. Celebrate 🎉\n\nLet us know if you need help!"
