name: Close Newfork Welcome & Follow Up

on:
  issue_comment:
    types: [created]

jobs:
  close-and-followup:
    runs-on: ubuntu-latest

    # Only act on issues labeled "newfork"
    if: contains(github.event.issue.labels.*.name, 'newfork')

    steps:
      - name: Extract FORK_FULL_NAME from comment
        id: extract
        run: |
          COMMENT_BODY="${{ github.event.issue.body }}"
          FORK_REPO="$(echo "$COMMENT_BODY" | grep -oP 'Fork full name: `\K[^`]+')"
      - name: Close issue if comment has no question mark
        if: "!contains(steps.vars.outputs.comment, '?')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Closing issue #${{ steps.vars.outputs.issue_number }}"
          gh issue close "${{ steps.vars.outputs.issue_number }}" \
            --repo "${{ github.repository }}" \
            --comment "✅ Closing this issue — looks like @$COMMENTER is all set!"

      - name: Create follow-up issue in the fork
        if: "!contains(steps.vars.outputs.comment, '?')"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSSREPO }}
          FORK_REPO: ${{ steps.vars.outputs.fork_repo }}
        run: |
          gh issue create \
            --repo "$FORK_REPO" \
            --title "📦 Next Steps for Your Fork" \
            --body "Hi\n\nYou're all set! Here are the next steps for the workshop:\n\n1. Do this\n2. Check that\n3. Celebrate 🎉\n\nLet us know if you need help!"
